### PR TITLE
Update homework file

### PR DESCRIPTION
**Pull request by dahachm**
**Update homework content** 

Deleted previouse content of "homework" file. 
Added "Hello GitHub" to "homework" file.

@dahachm 
@SagurovA93

### CODE REVIEW

**Comment by SagurovA93** [comment]
Is it still required to review this PR?

**Comment by dahachm** [comment]
@SagurovA93 

The task was to assign You as reviewer :)

Should I just close this PR?

**Comment by SagurovA93** [comment]
Yes, it's reviewed )

**Comment by dahachm** [comment]
> Yes, it's reviewed )

Is it? o.o

image

**Review by SagurovA93 — APPROVED** [review]
it's reviewed :)

**Pull request merged**
